version: '3'
services:
  php-fpm:
    image: php:7.4.7-fpm-alpine
    volumes:
      - ${APP_FOLDER}:/var/www/laravel
  nginx:
    build: ./nginx
    volumes:
      - ${APP_FOLDER}/public:/var/www/laravel/public
    ports: 
      - 80:80
    depends_on: 
      - php-fpm
  workspace:
    build: ./workspace
    tty: true
    working_dir: /workspace
    volumes:
      - ${APP_FOLDER}:/workspace
