version: '3'
services:
  php-fpm:
    build: ./php-fpm
    volumes:
      - ${APP_FOLDER}:/var/www/laravel
  nginx:
    build: ./nginx
    volumes:
      - ${APP_FOLDER}/public:/var/www/laravel/public
    ports: 
      - 80:80
    depends_on: 
      - php-fpm
  redis:
    image: redis
  mysql:
    image: mysql
    environment: 
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
  workspace:
    build: ./workspace
    tty: true
    working_dir: /workspace
    volumes:
      - ${APP_FOLDER}:/workspace
volumes:
  mysql-data:
